export const productsList = {
  contents: [
    {
      id: 10,
      name: 'New product 10',
      slug: 'test-4',
      brand: 'New brand',
      price: 500,
      available: true,
      featured: false,
      newArrival: true,
      withVariant: true,
      thumbnail:
        'http://localhost/images/product/product-image-10-20240719133636.png',
      status: 'PUBLISHED',
      discount: {
        id: 1,
        title: 'TEST',
        value: 10,
        type: 'PERCENTAGE',
      },
      category: {
        id: 1,
        lft: 1,
        rgt: 2,
        name: 'TEST',
        slug: 'test',
        featured: true,
        names: [
          {
            lang: 'en',
            name: 'TEST',
          },
          {
            lang: 'mm',
            name: '123123',
          },
        ],
      },
      audit: {
        createdAt: 1721396196621,
        createdBy: '18',
        modifiedAt: 1721726881774,
        modifiedBy: '18',
      },
    },
    {
      id: 9,
      name: 'TEST 9',
      slug: 'test-3',
      brand: 'New brand',
      price: 900,
      available: true,
      featured: false,
      newArrival: true,
      withVariant: true,
      thumbnail:
        'http://localhost/images/product/product-image-9-20240719132338.png',
      status: 'PUBLISHED',
      discount: {
        id: 1,
        title: 'TEST',
        value: 10,
        type: 'PERCENTAGE',
      },
      category: {
        id: 1,
        lft: 1,
        rgt: 2,
        name: 'TEST',
        slug: 'test',
        featured: true,
        names: [
          {
            lang: 'en',
            name: 'TEST',
          },
          {
            lang: 'mm',
            name: '123123',
          },
        ],
      },
      audit: {
        createdAt: 1721395418677,
        createdBy: '18',
        modifiedAt: 1721726942301,
        modifiedBy: '18',
      },
    },
    {
      id: 6,
      name: 'New product 6',
      slug: 'test-2',
      brand: 'New brand',
      price: 600,
      available: true,
      featured: true,
      newArrival: true,
      withVariant: true,
      thumbnail:
        'http://localhost/images/product/product-image-6-20240718144618.png',
      status: 'PUBLISHED',
      discount: {
        id: 1,
        title: 'TEST',
        value: 10,
        type: 'PERCENTAGE',
      },
      category: {
        id: 1,
        lft: 1,
        rgt: 2,
        name: 'TEST',
        slug: 'test',
        featured: true,
        names: [
          {
            lang: 'en',
            name: 'TEST',
          },
          {
            lang: 'mm',
            name: '123123',
          },
        ],
      },
      audit: {
        createdAt: 1721313978502,
        createdBy: '18',
        modifiedAt: 1721726890918,
        modifiedBy: '18',
      },
    },
    {
      id: 5,
      name: 'TEST 5',
      slug: 'test-1',
      brand: 'New brand',
      price: 5000,
      available: true,
      featured: true,
      newArrival: true,
      withVariant: true,
      thumbnail:
        'http://localhost/images/product/product-image-5-20240718144247.png',
      status: 'PUBLISHED',
      category: {
        id: 1,
        lft: 1,
        rgt: 2,
        name: 'TEST',
        slug: 'test',
        featured: true,
        names: [
          {
            lang: 'en',
            name: 'TEST',
          },
          {
            lang: 'mm',
            name: '123123',
          },
        ],
      },
      audit: {
        createdAt: 1721313767200,
        createdBy: '18',
        modifiedAt: 1721727019490,
        modifiedBy: '18',
      },
    },
    {
      id: 4,
      name: 'New product',
      slug: 'test',
      brand: 'New brand',
      price: 1000,
      available: true,
      featured: false,
      newArrival: true,
      withVariant: true,
      thumbnail:
        'http://localhost/images/product/product-image-4-20240718144054.jpg',
      status: 'PUBLISHED',
      discount: {
        id: 1,
        title: 'TEST',
        value: 10,
        type: 'PERCENTAGE',
      },
      category: {
        id: 1,
        lft: 1,
        rgt: 2,
        name: 'TEST',
        slug: 'test',
        featured: true,
        names: [
          {
            lang: 'en',
            name: 'TEST',
          },
          {
            lang: 'mm',
            name: '123123',
          },
        ],
      },
      audit: {
        createdAt: 1721313654751,
        createdBy: '18',
        modifiedAt: 1721726850639,
        modifiedBy: '18',
      },
    },
  ],
  totalPage: 1,
  currentPage: 0,
  pageSize: 5,
  totalElements: 5,
};
