export const user1 = {
  id: 1,
  name: 'multiplan-marketplace',
  email: 'romlev13@gmail.com',
  role: 'ADMIN',
  disabled: false,
  permissions: [],
  audit: {
    createdAt: 1720525427422,
    modifiedAt: 1720525427422,
  },
};
export const user2 = {
  id: 2,
  name: 'admin',
  phone: '+7-999-987-65-34',
  email: 'admin@mail.ru',
  role: 'OWNER',
  disabled: false,
  permissions: [
    'DASHBOARD_READ',
    'BANNER_READ',
    'BANNER_WRITE',
    'CATEGORY_READ',
    'CATEGORY_WRITE',
    'CITY_READ',
    'CITY_WRITE',
    'SHOP_READ',
    'SHOP_WRITE',
    'PRODUCT_READ',
    'PRODUCT_WRITE',
    'USER_READ',
    'USER_WRITE',
    'SUBSCRIPTION_PLAN_READ',
    'SUBSCRIPTION_PLAN_WRITE',
    'PROMO_CODE_READ',
    'PROMO_CODE_WRITE',
    'SUBSCRIPTION_HISTORY_READ',
    'SITE_SETTING_WRITE',
  ],
  audit: {
    createdAt: 1720628419760,
    modifiedAt: 1720628419760,
  },
};
